# Generated by Django 4.2.30 on 2026-06-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0011_flotavehiculo_aceite_clasificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Insumo / Repuesto')),
                ('categoria', models.CharField(help_text='Ej: Aceites, Neumáticos, Filtros, Limpieza', max_length=100, verbose_name='Categoría')),
                ('unidad_medida', models.CharField(choices=[('Unidad', 'Unidad(es)'), ('Litro', 'Litro(s)'), ('Paila', 'Paila(s)'), ('Kilo', 'Kilo(s)'), ('Bulto', 'Bulto(s)'), ('Par', 'Par(es)'), ('Galon', 'Galón/Galones'), ('Tambor', 'Tambor(es)')], default='Unidad', max_length=50, verbose_name='Unidad de Medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Mínimo Alerta')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción o Detalles')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Reabastecimiento)'), ('SALIDA', 'Salida (Asignación/Uso)')], max_length=15, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Motivo')),
                ('responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registrado por / Entregado a')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventory.insumo', verbose_name='Insumo')),
                ('vehiculo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_asignados', to='fleet.flotavehiculo', verbose_name='Vehículo Destino')),
            ],
            options={
                'verbose_name': 'Movimiento de Insumo',
                'verbose_name_plural': 'Movimientos de Insumos',
                'ordering': ['-fecha'],
            },
        ),
    ]
