# Generated by Django 4.2.30 on 2026-06-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/', verbose_name='Foto de Referencia'),
        ),
    ]
