# Generated by Django 4.2.30 on 2026-06-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_insumo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(default='Unidad', max_length=50, verbose_name='Unidad de Medida'),
        ),
    ]
