# Generated by Django 4.2.30 on 2026-04-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlotaVehiculo',
            fields=[
                ('placa', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.SmallIntegerField(verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('capacidad', models.SmallIntegerField(help_text='Capacidad Sentados')),
                ('capacidad_pie', models.SmallIntegerField(blank=True, help_text='Capacidad Parados', null=True)),
                ('aire_acondicionado', models.BooleanField(default=False)),
                ('accesibilidad', models.BooleanField(default=False, verbose_name='Rampa/Accesibilidad')),
                ('seguro_vence', models.DateField(blank=True, null=True)),
                ('revision_tecnica_vence', models.DateField(blank=True, null=True)),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.tipocombustible')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.modalidad')),
                ('submodalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.submodalidad')),
                ('transmision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.tipotransmision')),
            ],
            options={
                'verbose_name_plural': 'Flota de Vehículos',
            },
        ),
        migrations.CreateModel(
            name='VehiculoOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='organizations.empresaorganizacion')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizaciones', to='fleet.flotavehiculo')),
            ],
            options={
                'verbose_name_plural': 'Relaciones Vehículo-Organización',
            },
        ),
    ]
