# Generated by Django 4.2.30 on 2026-04-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flotavehiculo',
            options={'verbose_name': 'Vehículo de la Flota', 'verbose_name_plural': 'Flota de Vehículos'},
        ),
        migrations.AlterModelTable(
            name='flotavehiculo',
            table='flota_vehiculo',
        ),
        migrations.AlterModelTable(
            name='vehiculoorganizacion',
            table='vehiculo_organizacion',
        ),
    ]
