# Generated by Django 4.2.30 on 2026-05-05 14:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_rolpermiso'),
        ('fleet', '0002_alter_flotavehiculo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('Principal', 'Principal'), ('Secundario', 'Secundario'), ('Parada', 'Parada de Transferencia')], default='Principal', max_length=50)),
                ('capacidad_andenes', models.SmallIntegerField(default=0)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Mantenimiento', 'En Mantenimiento'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminales', to='catalogs.territoriomunicipio')),
            ],
            options={
                'verbose_name_plural': 'Terminales',
                'db_table': 'terminal',
            },
        ),
    ]
