# Generated by Django 4.2.30 on 2026-05-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_operadororganizacion_table_and_more'),
        ('fleet', '0003_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_asignados', to='personnel.personaloperador')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores_asignados', to='fleet.flotavehiculo')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones Vehículo-Operador',
                'db_table': 'vehiculo_operador',
                'unique_together': {('vehiculo', 'operador')},
            },
        ),
    ]
