# Generated by Django 4.2.30 on 2026-05-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_vehiculooperador'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotavehiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Foto del Vehículo'),
        ),
    ]
