# Generated by Django 4.2.30 on 2026-05-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_personaloperador_foto'),
        ('routes', '0004_gestionpermiso_frecuencia_ida_min_and_more'),
        ('fleet', '0005_flotavehiculo_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flotavehiculo',
            name='capacidad_pie',
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='certificado_vence',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Certificado de Circulación'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='cps',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de CPS (DT9/DT10)'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='propietario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='propietario_identificacion',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Identificación Propietario'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='rcv_vence',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento RCV'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='serial_carroceria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial de Carrocería'),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='capacidad',
            field=models.SmallIntegerField(help_text='Capacidad de pasajeros'),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='revision_tecnica_vence',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Revisión Técnica'),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='seguro_vence',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Seguro de Casco'),
        ),
        migrations.CreateModel(
            name='AsignacionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ruta', to='personnel.personaloperador')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_operativas', to='routes.vialidadruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ruta', to='fleet.flotavehiculo')),
            ],
            options={
                'verbose_name': 'Asignación de Ruta',
                'verbose_name_plural': 'Asignaciones de Rutas',
                'db_table': 'asignacion_ruta',
            },
        ),
    ]
