# Generated by Django 4.2.30 on 2026-05-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_personaloperador_foto'),
        ('routes', '0003_alter_gestionpermiso_table_alter_vialidadruta_table'),
        ('fleet', '0005_flotavehiculo_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ruta', to='personnel.personaloperador')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_operativas', to='routes.vialidadruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ruta', to='fleet.flotavehiculo')),
            ],
            options={
                'verbose_name': 'Asignación de Ruta',
                'verbose_name_plural': 'Asignaciones de Rutas',
                'db_table': 'asignacion_ruta',
            },
        ),
    ]
