# Generated by Django 4.2.30 on 2026-05-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_revision_1_cambios'),
        ('fleet', '0005_flotavehiculo_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flotavehiculo',
            name='capacidad_pie',
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='cps_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.tipocps', verbose_name='Tipo de CPS (DT9/DT10)'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='propietario_cedula',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cédula Propietario'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='propietario_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='propietario_rif',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='RIF Propietario'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='serial_carroceria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial de Carrocería'),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='capacidad',
            field=models.SmallIntegerField(help_text='Capacidad de pasajeros'),
        ),
    ]
