# Generated by Django 4.2.30 on 2026-05-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_gestionpermiso_frecuencia_ida_min_and_more'),
        ('fleet', '0006_remove_flotavehiculo_capacidad_pie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionruta',
            name='ruta',
        ),
        migrations.AddField(
            model_name='asignacionruta',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_operativas', to='routes.horarioruta'),
        ),
    ]
