# Generated by Django 4.2.30 on 2026-05-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_asignacionruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flotavehiculo',
            name='capacidad_pie',
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='cps',
            field=models.CharField(blank=True, choices=[('DT9', 'DT9'), ('DT10', 'DT10')], max_length=10, null=True, verbose_name='CPS'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='propietario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='propietario_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cédula/RIF del Propietario'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='serial_carroceria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial de Carrocería'),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='capacidad',
            field=models.SmallIntegerField(verbose_name='Capacidad'),
        ),
    ]
