# Generated by Django 4.2.30 on 2026-05-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_remove_flotavehiculo_capacidad_pie_flotavehiculo_cps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotavehiculo',
            name='certificado_vence',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Certificado de Circulación'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='rcv_vence',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento RCV'),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='revision_tecnica_vence',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Revisión Técnica'),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='seguro_vence',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Seguro de Casco'),
        ),
    ]
