# Generated by Django 4.2.30 on 2026-05-25 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_alter_configuracionvisual_nombre_sistema'),
        ('fleet', '0007_remove_asignacionruta_ruta_asignacionruta_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotavehiculo',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='anio',
            field=models.SmallIntegerField(blank=True, default=2026, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='capacidad',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Capacidad de pasajeros', null=True),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='marca',
            field=models.CharField(blank=True, default='No especificado', max_length=50),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='modelo',
            field=models.CharField(blank=True, default='No especificado', max_length=50),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='transmision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogs.tipotransmision'),
        ),
    ]
