# Generated by Django 4.2.30 on 2026-06-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_flotavehiculo_observaciones_alter_flotavehiculo_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotavehiculo',
            name='medida_cadena',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Medida de Cadena'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='serial_motor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial del Motor'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='tamano_caucho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tamaño de Caucho'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='tipo_aceite',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Aceite'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='tipo_rin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Rin'),
        ),
    ]
