# Generated by Django 4.2.30 on 2026-05-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_revision_1_cambios'),
        ('fleet', '0008_flotavehiculo_certificado_vence_and_more'),
    ]

    operations = [
    ]
