# Generated by Django 4.2.30 on 2026-06-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_flotavehiculo_medida_cadena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotavehiculo',
            name='detalles_mantenimiento_motor',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles Mantenimiento Motor'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='fecha_cambio_aceite',
            field=models.DateField(blank=True, null=True, verbose_name='Último Cambio de Aceite'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='fecha_mantenimiento_general',
            field=models.DateField(blank=True, null=True, verbose_name='Último Mantenimiento General'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='fecha_mantenimiento_motor',
            field=models.DateField(blank=True, null=True, verbose_name='Último Mantenimiento Motor'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='fecha_reemplazo_piezas',
            field=models.DateField(blank=True, null=True, verbose_name='Último Reemplazo Piezas'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='reemplazo_piezas_detalles',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles Reemplazo Piezas'),
        ),
    ]
