# Generated by Django 4.2.30 on 2026-06-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_flotavehiculo_detalles_mantenimiento_motor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotavehiculo',
            name='aceite_clasificacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clasificación de Aceite'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='aceite_marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca de Aceite'),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='serial_motor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial de Motor'),
        ),
        migrations.AlterField(
            model_name='flotavehiculo',
            name='tipo_aceite',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Aceite (Viscosidad)'),
        ),
    ]
