# Generated by Django 4.2.30 on 2026-06-04 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_personaloperador_certificado_saberes_and_more'),
        ('fleet', '0011_flotavehiculo_aceite_clasificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionruta',
            name='colector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ruta', to='personnel.personalcolector'),
        ),
    ]
