# Generated by Django 4.2.30 on 2026-06-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_empresaorganizacion_cupo_unidades'),
        ('routes', '0005_alter_horarioruta_sentido'),
        ('fleet', '0012_asignacionruta_colector'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionruta',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AddField(
            model_name='asignacionruta',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
        migrations.AddField(
            model_name='asignacionruta',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_operativas', to='organizations.empresaorganizacion'),
        ),
        migrations.AddField(
            model_name='asignacionruta',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_directas', to='routes.vialidadruta'),
        ),
        migrations.AlterField(
            model_name='asignacionruta',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_operativas', to='routes.horarioruta'),
        ),
    ]
