# Generated by Django 4.2.30 on 2026-06-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_add_ruta_org_direct_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotavehiculo',
            name='bateria_amperaje',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Amperaje de Batería'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='bateria_fecha_instalacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación Batería'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='bateria_marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca de Batería'),
        ),
        migrations.AddField(
            model_name='flotavehiculo',
            name='bateria_voltaje',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Voltaje de Batería'),
        ),
    ]
