# Generated by Django 4.2.30 on 2026-04-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalOperador',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('codigo_op', models.CharField(max_length=20, verbose_name='Código Operador')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('licencia_grado', models.SmallIntegerField(help_text='2, 3, 4, 5')),
                ('vence_lic', models.DateField(verbose_name='Vencimiento Licencia')),
                ('certificado_medico_vence', models.DateField(blank=True, null=True, verbose_name='Vencimiento Certificado Médico')),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Personal Operador',
            },
        ),
        migrations.CreateModel(
            name='OperadorOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_organizacion', to='personnel.personaloperador')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='organizations.empresaorganizacion')),
            ],
            options={
                'verbose_name_plural': 'Relaciones Operador-Organización',
            },
        ),
    ]
