# Generated by Django 4.2.30 on 2026-04-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaloperador',
            name='codigo_op',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código Operador'),
        ),
        migrations.AlterField(
            model_name='personaloperador',
            name='licencia_grado',
            field=models.SmallIntegerField(choices=[(2, '2da'), (3, '3ra'), (4, '4ta'), (5, '5ta')], help_text='2, 3, 4, 5'),
        ),
    ]
