# Generated by Django 4.2.30 on 2026-04-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_personaloperador_codigo_op_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operadororganizacion',
            table='operador_organizacion',
        ),
        migrations.AlterModelTable(
            name='personaloperador',
            table='personal_operador',
        ),
    ]
