# Generated by Django 4.2.30 on 2026-05-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_operadororganizacion_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaloperador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='operators/', verbose_name='Foto de Perfil'),
        ),
    ]
