# Generated by Django 4.2.30 on 2026-06-04 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_empresaorganizacion_cupo_unidades'),
        ('personnel', '0004_personaloperador_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalColector',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('codigo_col', models.CharField(max_length=20, unique=True, verbose_name='Código Colector')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='collectors/', verbose_name='Foto de Perfil')),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viudo(a)', 'Viudo(a)'), ('Concubinato', 'Concubinato')], max_length=20, null=True)),
                ('numero_hijos', models.PositiveIntegerField(default=0)),
                ('grado_instruccion', models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Bachiller', 'Bachiller'), ('TSU', 'TSU'), ('Universitario', 'Universitario'), ('Postgrado', 'Postgrado'), ('Ninguno', 'Ninguno')], max_length=20, null=True)),
                ('talla_camisa', models.CharField(blank=True, max_length=10, null=True)),
                ('talla_pantalon', models.CharField(blank=True, max_length=10, null=True)),
                ('talla_calzado', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Personal Colector',
                'db_table': 'personal_colector',
            },
        ),
        migrations.CreateModel(
            name='ColectorOrganizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('colector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_organizacion', to='personnel.personalcolector')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colectores', to='organizations.empresaorganizacion')),
            ],
            options={
                'verbose_name_plural': 'Relaciones Colector-Organización',
                'db_table': 'colector_organizacion',
            },
        ),
    ]
