# Generated by Django 4.2.30 on 2026-06-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_personalcolector_colectororganizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaloperador',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viudo(a)', 'Viudo(a)'), ('Concubinato', 'Concubinato')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personaloperador',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaloperador',
            name='grado_instruccion',
            field=models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Bachiller', 'Bachiller'), ('TSU', 'TSU'), ('Universitario', 'Universitario'), ('Postgrado', 'Postgrado'), ('Ninguno', 'Ninguno')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personaloperador',
            name='numero_hijos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personaloperador',
            name='talla_calzado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personaloperador',
            name='talla_camisa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personaloperador',
            name='talla_pantalon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
