# Generated by Django 4.2.30 on 2026-06-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_personaloperador_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcolector',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcolector',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalcolector',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personaloperador',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaloperador',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personaloperador',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
