# Generated by Django 4.2.30 on 2026-06-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_personalcolector_contacto_emergencia_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaloperador',
            name='certificado_saberes',
            field=models.BooleanField(default=False, verbose_name='¿Posee Certificado de Saberes?'),
        ),
        migrations.AddField(
            model_name='personaloperador',
            name='fecha_emision_saberes',
            field=models.DateField(blank=True, null=True, verbose_name='Emisión Cert. Saberes'),
        ),
        migrations.AddField(
            model_name='personaloperador',
            name='fecha_vencimiento_saberes',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Cert. Saberes'),
        ),
    ]
