# Generated by Django 4.2.30 on 2026-04-27 17:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VialidadRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('es_anillado', models.BooleanField(default=False)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tiempo_estimado_min', models.SmallIntegerField(blank=True, null=True)),
                ('numero_paradas', models.SmallIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('municipio_des', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='catalogs.territoriomunicipio', verbose_name='Municipio Destino')),
                ('municipio_or', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='catalogs.territoriomunicipio', verbose_name='Municipio Origen')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.tiporuta')),
                ('tipo_via', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.tipovia')),
            ],
            options={
                'verbose_name_plural': 'Vialidad y Rutas',
            },
        ),
        migrations.CreateModel(
            name='GestionPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('numero_resolucion', models.CharField(blank=True, max_length=50, null=True)),
                ('estatus', models.CharField(default='activo', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='organizations.empresaorganizacion')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='routes.vialidadruta')),
            ],
            options={
                'verbose_name_plural': 'Gestión de Permisos',
            },
        ),
    ]
