# Generated by Django 4.2.30 on 2026-04-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestionpermiso',
            options={'verbose_name': 'Permiso de Ruta', 'verbose_name_plural': 'Gestión de Permisos'},
        ),
        migrations.AlterField(
            model_name='gestionpermiso',
            name='estatus',
            field=models.CharField(choices=[('ACT', 'Activo'), ('SUSP', 'Suspendido')], default='ACT', max_length=15),
        ),
        migrations.AlterField(
            model_name='vialidadruta',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='gestionpermiso',
            unique_together={('org', 'ruta')},
        ),
    ]
