# Generated by Django 4.2.30 on 2026-04-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_gestionpermiso_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gestionpermiso',
            table='gestion_permiso',
        ),
        migrations.AlterModelTable(
            name='vialidadruta',
            table='vialidad_ruta',
        ),
    ]
