# Generated by Django 4.2.30 on 2026-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_gestionpermiso_table_alter_vialidadruta_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='vialidadruta',
            name='paradas',
            field=models.JSONField(blank=True, null=True, verbose_name='Paradas de la Ruta'),
        ),
    ]
