# Generated by Django 4.2.30 on 2026-05-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_gestionpermiso_table_alter_vialidadruta_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionpermiso',
            name='frecuencia_ida_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia Ida (min)'),
        ),
        migrations.AddField(
            model_name='gestionpermiso',
            name='frecuencia_vuelta_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia Vuelta (min)'),
        ),
        migrations.AddField(
            model_name='gestionpermiso',
            name='hora_regreso_ida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Regreso Ida'),
        ),
        migrations.AddField(
            model_name='gestionpermiso',
            name='hora_regreso_vuelta',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Regreso Vuelta'),
        ),
        migrations.AddField(
            model_name='gestionpermiso',
            name='hora_salida_ida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Salida Ida'),
        ),
        migrations.AddField(
            model_name='gestionpermiso',
            name='hora_salida_vuelta',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Salida Vuelta'),
        ),
        migrations.AddField(
            model_name='vialidadruta',
            name='paradas',
            field=models.JSONField(blank=True, null=True, verbose_name='Paradas de la Ruta'),
        ),
        migrations.CreateModel(
            name='HorarioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentido', models.CharField(choices=[('IDA', 'Ida'), ('VUELTA', 'Vuelta')], max_length=10)),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('frecuencia_minutos', models.SmallIntegerField(verbose_name='Frecuencia (minutos)')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='routes.gestionpermiso')),
            ],
            options={
                'verbose_name': 'Horario de Ruta',
                'verbose_name_plural': 'Horarios de Ruta',
                'db_table': 'horario_ruta',
            },
        ),
    ]
