# Generated by Django 4.2.30 on 2026-05-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_gestionpermiso_frecuencia_ida_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioruta',
            name='sentido',
            field=models.CharField(choices=[('IDA', 'Ida'), ('VUELTA', 'Vuelta'), ('SERVICIO', 'Servicio')], max_length=10),
        ),
    ]
