# Generated by Django 4.2 on 2026-05-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_vialidadruta_paradas'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionpermiso',
            name='frecuencia_ida_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia Ida (min)'),
        ),
        migrations.AddField(
            model_name='gestionpermiso',
            name='frecuencia_vuelta_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia Vuelta (min)'),
        ),
        migrations.AddField(
            model_name='gestionpermiso',
            name='hora_regreso_ida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Regreso Ida'),
        ),
        migrations.AddField(
            model_name='gestionpermiso',
            name='hora_regreso_vuelta',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Regreso Vuelta'),
        ),
        migrations.AddField(
            model_name='gestionpermiso',
            name='hora_salida_ida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Salida Ida'),
        ),
        migrations.AddField(
            model_name='gestionpermiso',
            name='hora_salida_vuelta',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Salida Vuelta'),
        ),
    ]
