# Generated by Django 4.2.30 on 2026-05-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_revision_1_cambios'),
        ('routes', '0005_gestionpermiso_horarios'),
    ]

    operations = [
    ]
