# Generated by Django 4.2.30 on 2026-04-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorioeje',
            name='color_hex',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
