# Generated by Django 4.2.30 on 2026-04-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_alter_territorioeje_color_hex'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modalidad',
            table='modalidad',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='submodalidad',
            table='submodalidad',
        ),
        migrations.AlterModelTable(
            name='territorioeje',
            table='territorio_eje',
        ),
        migrations.AlterModelTable(
            name='territoriomunicipio',
            table='territorio_municipio',
        ),
        migrations.AlterModelTable(
            name='tipocombustible',
            table='tipo_combustible',
        ),
        migrations.AlterModelTable(
            name='tipoorganizacion',
            table='tipo_organizacion',
        ),
        migrations.AlterModelTable(
            name='tiporuta',
            table='tipo_ruta',
        ),
        migrations.AlterModelTable(
            name='tipotransmision',
            table='tipo_transmision',
        ),
        migrations.AlterModelTable(
            name='tipovia',
            table='tipo_via',
        ),
    ]
