# Generated by Django 4.2.30 on 2026-05-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_modalidad_table_alter_rol_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=20)),
                ('permitido', models.BooleanField(default=False)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='catalogs.rol')),
            ],
            options={
                'verbose_name_plural': 'Permisos de Rol',
                'db_table': 'rol_permiso',
                'unique_together': {('rol', 'modulo', 'accion')},
            },
        ),
    ]
