# Generated by Django 4.2.30 on 2026-05-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_configuracionvisual'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de CPS',
                'verbose_name_plural': 'Tipos de CPS',
                'db_table': 'tipo_cps',
            },
        ),
    ]
