# Generated by Django 4.2.30 on 2026-05-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_revision_1_cambios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionvisual',
            name='nombre_sistema',
            field=models.CharField(default='Transporte Aragua Digital', max_length=100),
        ),
    ]
