# Generated by Django 4.2.30 on 2026-04-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaOrganizacion',
            fields=[
                ('rif', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255)),
                ('rep_legal_ci', models.CharField(max_length=15, verbose_name='Cédula Rep. Legal')),
                ('rep_legal_nom', models.CharField(max_length=150, verbose_name='Nombre Rep. Legal')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=255, null=True)),
                ('direccion_fiscal', models.TextField(blank=True, null=True)),
                ('fecha_constitucion', models.DateField(blank=True, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizaciones', to='catalogs.tipoorganizacion')),
            ],
            options={
                'verbose_name_plural': 'Empresas y Organizaciones',
            },
        ),
    ]
