# Generated by Django 4.2.30 on 2026-04-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresaorganizacion',
            options={'verbose_name': 'Empresa u Organización', 'verbose_name_plural': 'Empresas y Organizaciones'},
        ),
        migrations.AlterModelTable(
            name='empresaorganizacion',
            table='empresa_organizacion',
        ),
    ]
