# Generated by Django 4.2 on 2026-05-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_empresaorganizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaorganizacion',
            name='cupo_unidades',
            field=models.PositiveIntegerField(default=0, verbose_name='Cupo máximo de unidades'),
        ),
        migrations.AddField(
            model_name='empresaorganizacion',
            name='modalidad_cps',
            field=models.CharField(blank=True, choices=[('DT9', 'DT9 (5-32 Puestos)'), ('DT10', 'DT10 (32+ Puestos)')], max_length=10, null=True, verbose_name='Modalidad CPS'),
        ),
    ]
