# Generated by Django 4.2.30 on 2026-05-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_revision_1_cambios'),
        ('organizations', '0002_alter_empresaorganizacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=15, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('anio_creacion', models.SmallIntegerField(blank=True, null=True, verbose_name='Año de Creación')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Gremio',
                'verbose_name_plural': 'Gremios',
                'db_table': 'gremio',
            },
        ),
        migrations.RemoveField(
            model_name='empresaorganizacion',
            name='fecha_constitucion',
        ),
        migrations.AddField(
            model_name='empresaorganizacion',
            name='cupo_maximo_unidades',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Cupo Máximo de Unidades'),
        ),
        migrations.AddField(
            model_name='empresaorganizacion',
            name='fecha_constitucion_mercantil',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Constitución Mercantil'),
        ),
        migrations.AlterField(
            model_name='empresaorganizacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizaciones', to='catalogs.tipoorganizacion', verbose_name='Tipo de Organización'),
        ),
        migrations.CreateModel(
            name='OrganizacionCps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código del Permiso')),
                ('fecha_expedicion', models.DateField(verbose_name='Fecha de Expedición')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('modalidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modalidad (p.ej. Colectivo Suburbano)')),
                ('cupo_maximo_unidades', models.SmallIntegerField(blank=True, null=True, verbose_name='Cupo Máximo de Unidades')),
                ('activa', models.BooleanField(default=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cps_registros', to='organizations.empresaorganizacion')),
                ('tipo_cps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.tipocps', verbose_name='Tipo CPS')),
            ],
            options={
                'verbose_name': 'CPS de Organización',
                'verbose_name_plural': 'CPS de Organizaciones',
                'db_table': 'organizacion_cps',
            },
        ),
        migrations.AddField(
            model_name='empresaorganizacion',
            name='gremio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizaciones', to='organizations.gremio'),
        ),
    ]
