# Generated by Django 4.2.30 on 2026-05-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_revision_1_cambios'),
        ('organizations', '0003_gremio_remove_empresaorganizacion_fecha_constitucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaorganizacion',
            name='conteo_bus',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Bus'),
        ),
        migrations.AddField(
            model_name='empresaorganizacion',
            name='conteo_minibus',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Minibus'),
        ),
        migrations.AddField(
            model_name='empresaorganizacion',
            name='conteo_otro',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Otros'),
        ),
        migrations.AddField(
            model_name='empresaorganizacion',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.territoriomunicipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='empresaorganizacion',
            name='rutas_suburbanas',
            field=models.PositiveIntegerField(default=0, verbose_name='Rutas Suburbanas'),
        ),
        migrations.AddField(
            model_name='empresaorganizacion',
            name='rutas_urbanas',
            field=models.PositiveIntegerField(default=0, verbose_name='Rutas Urbanas'),
        ),
    ]
