# Generated by Django 4.2.30 on 2026-05-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_empresaorganizacion_cupos_cps'),
        ('organizations', '0003_revision_1_cambios'),
    ]

    operations = [
    ]
