# Generated by Django 4.2.30 on 2026-05-14 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_revision_1_cambios'),
        ('organizations', '0004_empresaorganizacion_conteo_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaorganizacion',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizaciones', to='catalogs.territoriomunicipio', verbose_name='Municipio Sede'),
        ),
    ]
