# Generated by Django 4.2.30 on 2026-05-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_empresaorganizacion_municipio'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='empresaorganizacion',
        #     name='cupo_unidades',
        #     field=models.PositiveIntegerField(default=0, verbose_name='Cupo Unidades'),
        # ),
        migrations.AlterField(
            model_name='empresaorganizacion',
            name='rep_legal_ci',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cédula Rep. Legal'),
        ),
        migrations.AlterField(
            model_name='empresaorganizacion',
            name='rep_legal_nom',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Rep. Legal'),
        ),
    ]
