# Generated by Django 4.2.30 on 2026-05-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_empresaorganizacion_cupo_unidades_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='empresaorganizacion',
        #     name='cupo_unidades',
        #     field=models.PositiveIntegerField(default=0, verbose_name='Cupo Unidades'),
        # ),
        migrations.AddField(
            model_name='empresaorganizacion',
            name='modalidad_cps',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Modalidad CPS'),
        ),
    ]
