# Generated by Django 4.2.30 on 2026-06-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_empresaorganizacion_cupo_unidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaorganizacion',
            name='cupo_unidades',
            field=models.PositiveIntegerField(default=0, verbose_name='Cupo Unidades'),
        ),
    ]
